# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1277941ca9218a536fa1a70d7230fd53237031cda5c4c62d1c3da136e0fd4496883514bbcc0743f18ab377628639562445fe429b9da0b3c3bd0a7e99843b7af

test:
  secret_key_base: fc25856501b04448ec173bb4f34928183649a609b8a71528d69fb7ca36c1903fa69a82b2503660737f56839b1e75da8b3bf46f8c7c4815c7bc02d5c39c77dbdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
